# This is a basic workflow to help you get started with Actions

name: generate_project_files

# Controls when the action will run. 
on: push
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  clone_tensorflow:
    runs-on: ubuntu-latest
    steps:
    
      - name: Clone this repo
        uses: actions/checkout@master
        with:
            path: .
         
      - name: Clone Tensorflow
        uses: actions/checkout@v2
        with:
          repository: tensorflow/tensorflow
          path: ./tensorflow-master

      - name: Set Up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade six
          
      - name: generate projects
        run: cd tensorflow-master && make -f tensorflow/lite/micro/tools/make/Makefile generate_hello_world_make_project 

      - name: copy tf over
        run: cp -r tensorflow-master/tensorflow/lite/micro/tools/make/gen/linux_x86_64_default/prj/hello_world/make/tensorflow .

      - name: copy 3rd party over
        run: cp -r tensorflow-master/tensorflow/lite/micro/tools/make/gen/linux_x86_64_default/prj/hello_world/make/third_party .
        
      - name: remove tensorflow
        run: rm -rf tensorflow-master

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update tflite-micro"
 
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

